### ISSUE TITLE
硬件清单有吗？能不能写一个手册式的文档，参考这个文档把你的代码跑起来？

### ISSUE THREAD

**Issue by forconz** [yunxiyinzhe/HouseMonitorPi#1]
室内空气质量，甲醛浓度 这两个用什么传感器做？

**Comment by yunxiyinzhe** [comment]
张大妈上写过文章：https://post.smzdm.com/p/590332/
一般我默认找到这个项目的都是从张大妈的这篇文章过来的。。。。

**Comment by forconz** [comment]
囧，我直接github搜的，这篇文章很好啊。只是细节，唉，自动动手咯~
我觉得产品化还是可行的，需要批量化生产才能大幅度降低成本，几百元是没问题的。

**Comment by forconz** [comment]
建议使用多合一的传感器 PTQS1005，温湿度 甲醛 VOC PM2.5 CO2全部都检测了。
